name: ginnovate.be
favicon: null
layout_spectrum: 0.6934402412734926
typography_spectrum: 0.18714726786129177
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#204c67'
    - '#1d1115'
    - '#869995'
    - '#fefdf9'
    - '#0afdf9'
  brandStrength: 0.5
  lightness: 0.45853162929415703
  saturation: 0.8489055321551859
  rhythmicContrast: 0.9352336244191974
purpose: []
