name: 'Nelicieuse '
favicon: null
layout_spectrum: 0.8865
typography_spectrum: 0.90086
title: 'Your healthy food place '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7c4f30'
    - '#472d1a'
    - '#dbcdbf'
    - '#b1a49b'
  brandStrength: 0.9375
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
