name: ginnovate.be
favicon: null
layout_spectrum: 0.6934402412734926
typography_spectrum: 0.18714726786129177
title: The pl
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#204c67'
    - '#1d1115'
    - '#869995'
    - '#fefdf9'
    - '#0afdf9'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
